// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { userControllerFindMeV1ResponseTransformer, userControllerFindOneV1ResponseTransformer, userControllerUpdateV1ResponseTransformer } from './transformers.gen';
import type { AuthControllerGetNewAccessTokenV1Data, AuthControllerGetNewAccessTokenV1Errors, AuthControllerGetNewAccessTokenV1Responses, AuthControllerHackClubAuthCallbackV1Data, AuthControllerHackClubAuthCallbackV1Errors, AuthControllerHackClubAuthCallbackV1Responses, AuthControllerHackClubAuthV1Data, AuthControllerHackClubAuthV1Errors, AuthControllerHackClubAuthV1Responses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, UserControllerFindMeV1Data, UserControllerFindMeV1Errors, UserControllerFindMeV1Responses, UserControllerFindOneV1Data, UserControllerFindOneV1Errors, UserControllerFindOneV1Responses, UserControllerRemoveV1Data, UserControllerRemoveV1Errors, UserControllerRemoveV1Responses, UserControllerUpdateV1Data, UserControllerUpdateV1Errors, UserControllerUpdateV1Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class health {
    /**
     * Check if server is running
     *
     * Check if server is up and running, check if database is running
     */
    public static healthCheck<ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({ url: '/api/v1/health', ...options });
    }
}

export class auth {
    /**
     * Sign in with Hack Club Auth
     *
     * Redirects the user to the Hack Club Auth sign in page<br>After the user authorizes your app, they'll be redirected to your redirect URI with an authorization code:
     * https://yourapp.com/callback?code=abc123def456
     */
    public static authControllerHackClubAuthV1<ThrowOnError extends boolean = false>(options: Options<AuthControllerHackClubAuthV1Data, ThrowOnError>) {
        return (options.client ?? client).get<AuthControllerHackClubAuthV1Responses, AuthControllerHackClubAuthV1Errors, ThrowOnError>({ url: '/api/v1/auth/hackclubauth', ...options });
    }
    
    /**
     * Exchange the code for an access token
     *
     * Exchange the code for an access token
     */
    public static authControllerHackClubAuthCallbackV1<ThrowOnError extends boolean = false>(options: Options<AuthControllerHackClubAuthCallbackV1Data, ThrowOnError>) {
        return (options.client ?? client).get<AuthControllerHackClubAuthCallbackV1Responses, AuthControllerHackClubAuthCallbackV1Errors, ThrowOnError>({ url: '/api/v1/auth/hackclubauth/callback', ...options });
    }
    
    /**
     * Get a new access token with a refresh token
     *
     * Get a new access token with a refresh token, 4 request per hour for each user, if the limit is exceeded, the user will be blocked for 2 hours to prevent abuse
     */
    public static authControllerGetNewAccessTokenV1<ThrowOnError extends boolean = false>(options: Options<AuthControllerGetNewAccessTokenV1Data, ThrowOnError>) {
        return (options.client ?? client).post<AuthControllerGetNewAccessTokenV1Responses, AuthControllerGetNewAccessTokenV1Errors, ThrowOnError>({
            url: '/api/v1/auth/token/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class user {
    /**
     * Get the current user
     *
     * Get the current user based on the JWT token provided in the request. This endpoint returns the user information associated with the token.
     */
    public static userControllerFindMeV1<ThrowOnError extends boolean = false>(options?: Options<UserControllerFindMeV1Data, ThrowOnError>) {
        return (options?.client ?? client).get<UserControllerFindMeV1Responses, UserControllerFindMeV1Errors, ThrowOnError>({
            responseTransformer: userControllerFindMeV1ResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/user/me',
            ...options
        });
    }
    
    public static userControllerRemoveV1<ThrowOnError extends boolean = false>(options: Options<UserControllerRemoveV1Data, ThrowOnError>) {
        return (options.client ?? client).delete<UserControllerRemoveV1Responses, UserControllerRemoveV1Errors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/user/{id}',
            ...options
        });
    }
    
    /**
     * Get a user by ID
     *
     * Get a user by their unique identifier (ID). This endpoint requires the ID parameter and returns the corresponding user information.
     */
    public static userControllerFindOneV1<ThrowOnError extends boolean = false>(options: Options<UserControllerFindOneV1Data, ThrowOnError>) {
        return (options.client ?? client).get<UserControllerFindOneV1Responses, UserControllerFindOneV1Errors, ThrowOnError>({
            responseTransformer: userControllerFindOneV1ResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/user/{id}',
            ...options
        });
    }
    
    /**
     * Update the current user profile
     *
     * Update the current user profile based on the JWT token provided in the request. This endpoint returns the new user information associated with the token.
     */
    public static userControllerUpdateV1<ThrowOnError extends boolean = false>(options: Options<UserControllerUpdateV1Data, ThrowOnError>) {
        return (options.client ?? client).patch<UserControllerUpdateV1Responses, UserControllerUpdateV1Errors, ThrowOnError>({
            responseTransformer: userControllerUpdateV1ResponseTransformer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/user/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
