// This file is auto-generated by @hey-api/openapi-ts

import type { MatchControllerConfirmMatchingV1Response, MatchControllerCreateV1Response, MatchControllerFinalizeMatchingV1Response, MatchControllerFindAllRelatingToMeV1Response, MatchControllerFindAllV1Response, MatchControllerFindOneV1Response, ProjectPitchControllerCreateV1Response, ProjectPitchControllerFindAllV1Response, ProjectPitchControllerFindMyProjectPitchesV1Response, ProjectPitchControllerFindOneV1Response, ProjectPitchControllerSearchV1Response, ProjectPitchControllerUpdateV1Response, UserControllerFindMeV1Response, UserControllerFindOneV1Response } from './types.gen';

const userResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const userControllerFindMeV1ResponseTransformer = async (data: any): Promise<UserControllerFindMeV1Response> => {
    data = userResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const userControllerFindOneV1ResponseTransformer = async (data: any): Promise<UserControllerFindOneV1Response> => {
    data = userResponseDtoSchemaResponseTransformer(data);
    return data;
};

const projectPitchResponseDtoSchemaResponseTransformer = (data: any) => {
    data.user = userResponseDtoSchemaResponseTransformer(data.user);
    return data;
};

export const projectPitchControllerFindAllV1ResponseTransformer = async (data: any): Promise<ProjectPitchControllerFindAllV1Response> => {
    data = data.map((item: any) => projectPitchResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const projectPitchControllerCreateV1ResponseTransformer = async (data: any): Promise<ProjectPitchControllerCreateV1Response> => {
    data = projectPitchResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const projectPitchControllerSearchV1ResponseTransformer = async (data: any): Promise<ProjectPitchControllerSearchV1Response> => {
    data = data.map((item: any) => projectPitchResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const projectPitchControllerFindMyProjectPitchesV1ResponseTransformer = async (data: any): Promise<ProjectPitchControllerFindMyProjectPitchesV1Response> => {
    data = data.map((item: any) => projectPitchResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const projectPitchControllerFindOneV1ResponseTransformer = async (data: any): Promise<ProjectPitchControllerFindOneV1Response> => {
    data = projectPitchResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const projectPitchControllerUpdateV1ResponseTransformer = async (data: any): Promise<ProjectPitchControllerUpdateV1Response> => {
    data = projectPitchResponseDtoSchemaResponseTransformer(data);
    return data;
};

const matchResponseDtoSchemaResponseTransformer = (data: any) => {
    data.projectOwner = userResponseDtoSchemaResponseTransformer(data.projectOwner);
    data.collaboratingUser = userResponseDtoSchemaResponseTransformer(data.collaboratingUser);
    return data;
};

export const matchControllerCreateV1ResponseTransformer = async (data: any): Promise<MatchControllerCreateV1Response> => {
    data = matchResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const matchControllerFindAllRelatingToMeV1ResponseTransformer = async (data: any): Promise<MatchControllerFindAllRelatingToMeV1Response> => {
    data = data.map((item: any) => matchResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const matchControllerFindAllV1ResponseTransformer = async (data: any): Promise<MatchControllerFindAllV1Response> => {
    data = data.map((item: any) => matchResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const matchControllerFindOneV1ResponseTransformer = async (data: any): Promise<MatchControllerFindOneV1Response> => {
    data = matchResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const matchControllerConfirmMatchingV1ResponseTransformer = async (data: any): Promise<MatchControllerConfirmMatchingV1Response> => {
    data = matchResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const matchControllerFinalizeMatchingV1ResponseTransformer = async (data: any): Promise<MatchControllerFinalizeMatchingV1Response> => {
    data = matchResponseDtoSchemaResponseTransformer(data);
    return data;
};
