// This file is auto-generated by @hey-api/openapi-ts

import type { UserControllerFindMeV1Response, UserControllerFindOneV1Response } from './types.gen';

const userResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const userControllerFindMeV1ResponseTransformer = async (data: any): Promise<UserControllerFindMeV1Response> => {
    data = userResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const userControllerFindOneV1ResponseTransformer = async (data: any): Promise<UserControllerFindOneV1Response> => {
    data = userResponseDtoSchemaResponseTransformer(data);
    return data;
};
