// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://shipmates-server.onrender.com' | (string & {});
};

export type ErrorMessageDto = {
    /**
     *
     * HTTP status code to be expected and their meanings
     *
     * 200 - Request was successful
     *
     * 201 - Request was successful and a new resource was created
     *
     * 400 - Request failed due to bad request, invalid data, or request body syntax error
     *
     * 401 - Unauthorized request (Request requires authentication)
     *
     * 403 - Request was authorized but cannot be completed (e.g due to roles restrictions)
     *
     * 404 - Resource not found
     *
     * 422 - Request was received but cannot be processed
     *
     * 500 - Internal Server error
     *
     */
    readonly statusCode: number;
    /**
     * Human readable error message
     */
    message: string | Array<string>;
    /**
     * Machine readable error message
     */
    readonly error?: string;
};

export type AuthCallbackResponseDto = {
    /**
     * The access token to be used for authenticated requests
     */
    access_token: string;
    /**
     * The refresh token to be used for renew access token (can only be used once)
     */
    refresh_token: string;
};

export type GetNewAccessTokenDto = {
    /**
     * Refresh token to generate a new access token
     */
    refresh_token: string;
};

export type GetNewAccessTokenResponseDto = {
    /**
     * The new access token to be used for authenticated requests
     */
    access_token: string;
};

export type UserResponseDto = {
    /**
     * The unique identifier of the user
     */
    id: string;
    /**
     * The hack club unique identifier of the user
     */
    hcId: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * The slack unique identifier of the user
     */
    slackId: string | null;
    /**
     * The first name of the user
     */
    firstName: string | null;
    /**
     * The last name of the user
     */
    lastName: string | null;
    /**
     * The profile image of the user
     */
    profileImg: string | null;
    /**
     * Whether the user is eligible for the YSWS program
     */
    yswsEligible: boolean;
    /**
     * When the user account was created
     */
    createdAt: Date;
    /**
     * When last the user account was updated
     */
    updatedAt: Date;
};

export type ErrorMessageDtoWritable = {
    /**
     * Human readable error message
     */
    message: string | Array<string>;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type AuthControllerHackClubAuthV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * The URI to redirect to after signing in
         */
        redirect_uri: string;
    };
    url: '/api/v1/auth/hackclubauth';
};

export type AuthControllerHackClubAuthV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type AuthControllerHackClubAuthV1Error = AuthControllerHackClubAuthV1Errors[keyof AuthControllerHackClubAuthV1Errors];

export type AuthControllerHackClubAuthV1Responses = {
    200: unknown;
};

export type AuthControllerHackClubAuthCallbackV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * The code return from the redirect from the Hack Club Auth sign in page
         */
        code: string;
        /**
         * The URI to redirect to after signing in
         */
        redirect_uri: string;
    };
    url: '/api/v1/auth/hackclubauth/callback';
};

export type AuthControllerHackClubAuthCallbackV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type AuthControllerHackClubAuthCallbackV1Error = AuthControllerHackClubAuthCallbackV1Errors[keyof AuthControllerHackClubAuthCallbackV1Errors];

export type AuthControllerHackClubAuthCallbackV1Responses = {
    200: AuthCallbackResponseDto;
};

export type AuthControllerHackClubAuthCallbackV1Response = AuthControllerHackClubAuthCallbackV1Responses[keyof AuthControllerHackClubAuthCallbackV1Responses];

export type AuthControllerGetNewAccessTokenV1Data = {
    body: GetNewAccessTokenDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token/refresh';
};

export type AuthControllerGetNewAccessTokenV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type AuthControllerGetNewAccessTokenV1Error = AuthControllerGetNewAccessTokenV1Errors[keyof AuthControllerGetNewAccessTokenV1Errors];

export type AuthControllerGetNewAccessTokenV1Responses = {
    200: GetNewAccessTokenResponseDto;
};

export type AuthControllerGetNewAccessTokenV1Response = AuthControllerGetNewAccessTokenV1Responses[keyof AuthControllerGetNewAccessTokenV1Responses];

export type UserControllerFindMeV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type UserControllerFindMeV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type UserControllerFindMeV1Error = UserControllerFindMeV1Errors[keyof UserControllerFindMeV1Errors];

export type UserControllerFindMeV1Responses = {
    200: UserResponseDto;
};

export type UserControllerFindMeV1Response = UserControllerFindMeV1Responses[keyof UserControllerFindMeV1Responses];

export type UserControllerFindOneV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/user/{id}';
};

export type UserControllerFindOneV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type UserControllerFindOneV1Error = UserControllerFindOneV1Errors[keyof UserControllerFindOneV1Errors];

export type UserControllerFindOneV1Responses = {
    200: UserResponseDto;
};

export type UserControllerFindOneV1Response = UserControllerFindOneV1Responses[keyof UserControllerFindOneV1Responses];
