// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://shipmates-server.onrender.com' | (string & {});
};

export type ErrorMessageDto = {
    /**
     *
     * HTTP status code to be expected and their meanings
     *
     * 200 - Request was successful
     *
     * 201 - Request was successful and a new resource was created
     *
     * 400 - Request failed due to bad request, invalid data, or request body syntax error
     *
     * 401 - Unauthorized request (Request requires authentication)
     *
     * 403 - Request was authorized but cannot be completed (e.g due to roles restrictions)
     *
     * 404 - Resource not found
     *
     * 422 - Request was received but cannot be processed
     *
     * 500 - Internal Server error
     *
     */
    readonly statusCode: number;
    /**
     * Human readable error message
     */
    message: string | Array<string>;
    /**
     * Machine readable error message
     */
    readonly error?: string;
};

export type AuthCallbackResponseDto = {
    /**
     * The access token to be used for authenticated requests
     */
    access_token: string;
    /**
     * The refresh token to be used for renew access token (can only be used once)
     */
    refresh_token: string;
};

export type GetNewAccessTokenDto = {
    /**
     * Refresh token to generate a new access token
     */
    refresh_token: string;
};

export type GetNewAccessTokenResponseDto = {
    /**
     * The new access token to be used for authenticated requests
     */
    access_token: string;
};

export type UserResponseDto = {
    /**
     * The unique identifier of the user
     */
    id: string;
    /**
     * The hack club unique identifier of the user
     */
    hcId: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * The slack unique identifier of the user
     */
    slackId: string | null;
    /**
     * The first name of the user
     */
    firstName: string | null;
    /**
     * The last name of the user
     */
    lastName: string | null;
    /**
     * The profile image of the user
     */
    profileImg: string | null;
    /**
     * Whether the user is eligible for the YSWS program
     */
    yswsEligible: boolean;
    /**
     * When the user account was created
     */
    createdAt: Date;
    /**
     * When last the user account was updated
     */
    updatedAt: Date;
};

export type SkillDto = {
    /**
     * id of the skill needed for the project
     */
    id: string;
};

export type CreateSkillDto = {
    /**
     * The name of the skill to be added
     */
    name: string;
};

export type CreateProjectPitchDto = {
    /**
     * Title of the project to be pitched
     */
    projectTitle: string;
    /**
     * The description of what needed for the project
     */
    pitchDescription: string;
    /**
     * List of skills needed(to be added) for the project. **Skill already exist in database**
     */
    skills: Array<SkillDto>;
    /**
     * List of skills needed for the project. **Skill do not exist in database**
     */
    newSkills: Array<CreateSkillDto>;
};

export type SkillResponseDto = {
    /**
     * ID of the skill
     */
    id: string;
    /**
     * Name of the skill
     */
    name: string;
    /**
     * The date the skill was created
     */
    createdAt: string;
    /**
     * The data the skill was last updated
     */
    updatedAt: string;
};

export type ProjectPitchResponseDto = {
    /**
     * ID of the project
     */
    id: string;
    /**
     * Title of the project to be pitched
     */
    title: string;
    /**
     * The description of what needed for the project
     */
    description: string;
    /**
     * The description of what needed for the project
     */
    skillsNeeded: Array<SkillResponseDto>;
    /**
     * The user who created the project pitch
     */
    user: UserResponseDto;
    /**
     * The userId of user who created the project pitch
     */
    userId: string;
    /**
     * The date the project pitch was created
     */
    createdAt: string;
    /**
     * The data the project pitch was last updated
     */
    updatedAt: string;
};

export type UpdateProjectPitchDto = {
    /**
     * Title of the project to be pitched
     */
    projectTitle?: string;
    /**
     * The description of what needed for the project
     */
    pitchDescription?: string;
    /**
     * List of skills needed(to be added) for the project. Skill already exist in database
     * **Note: Override the skillsNeeded array if provided**
     */
    skills?: Array<SkillDto>;
    /**
     * List of skills needed for the project. **Skill do not exist in database**
     */
    newSkills?: Array<CreateSkillDto>;
};

export type GeneralOkResponseDto = {
    /**
     * Human readable message
     */
    message: string;
};

export type YsWsResponseDto = {
    /**
     * Name of the YSWS program
     */
    name: string;
    /**
     * When the YSWS  program ends
     */
    deadline: string;
    /**
     * Description of the YSWS program
     */
    description: string;
    /**
     * Website of the YSWS program
     */
    website: string | null;
    /**
     * Slack channel link for the YSWS program
     */
    slack: string | null;
    /**
     * Slack channel name for the YSWS program (begins with # i.e #shipmates)
     */
    slackChannel: string | null;
    /**
     * Status of the YSWS program
     */
    status: 'active' | 'ended' | 'draft';
};

export type ErrorMessageDtoWritable = {
    /**
     * Human readable error message
     */
    message: string | Array<string>;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type AuthControllerHackClubAuthV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * The URI to redirect to after signing in
         */
        redirect_uri: string;
    };
    url: '/api/v1/auth/hackclubauth';
};

export type AuthControllerHackClubAuthV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type AuthControllerHackClubAuthV1Error = AuthControllerHackClubAuthV1Errors[keyof AuthControllerHackClubAuthV1Errors];

export type AuthControllerHackClubAuthV1Responses = {
    200: unknown;
};

export type AuthControllerHackClubAuthCallbackV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * The code return from the redirect from the Hack Club Auth sign in page
         */
        code: string;
        /**
         * The URI to redirect to after signing in
         */
        redirect_uri: string;
    };
    url: '/api/v1/auth/hackclubauth/callback';
};

export type AuthControllerHackClubAuthCallbackV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type AuthControllerHackClubAuthCallbackV1Error = AuthControllerHackClubAuthCallbackV1Errors[keyof AuthControllerHackClubAuthCallbackV1Errors];

export type AuthControllerHackClubAuthCallbackV1Responses = {
    200: AuthCallbackResponseDto;
};

export type AuthControllerHackClubAuthCallbackV1Response = AuthControllerHackClubAuthCallbackV1Responses[keyof AuthControllerHackClubAuthCallbackV1Responses];

export type AuthControllerGetNewAccessTokenV1Data = {
    body: GetNewAccessTokenDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token/refresh';
};

export type AuthControllerGetNewAccessTokenV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type AuthControllerGetNewAccessTokenV1Error = AuthControllerGetNewAccessTokenV1Errors[keyof AuthControllerGetNewAccessTokenV1Errors];

export type AuthControllerGetNewAccessTokenV1Responses = {
    200: GetNewAccessTokenResponseDto;
};

export type AuthControllerGetNewAccessTokenV1Response = AuthControllerGetNewAccessTokenV1Responses[keyof AuthControllerGetNewAccessTokenV1Responses];

export type UserControllerFindMeV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type UserControllerFindMeV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type UserControllerFindMeV1Error = UserControllerFindMeV1Errors[keyof UserControllerFindMeV1Errors];

export type UserControllerFindMeV1Responses = {
    200: UserResponseDto;
};

export type UserControllerFindMeV1Response = UserControllerFindMeV1Responses[keyof UserControllerFindMeV1Responses];

export type UserControllerFindOneV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/user/{id}';
};

export type UserControllerFindOneV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type UserControllerFindOneV1Error = UserControllerFindOneV1Errors[keyof UserControllerFindOneV1Errors];

export type UserControllerFindOneV1Responses = {
    200: UserResponseDto;
};

export type UserControllerFindOneV1Response = UserControllerFindOneV1Responses[keyof UserControllerFindOneV1Responses];

export type ProjectPitchControllerFindAllV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project-pitch';
};

export type ProjectPitchControllerFindAllV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type ProjectPitchControllerFindAllV1Error = ProjectPitchControllerFindAllV1Errors[keyof ProjectPitchControllerFindAllV1Errors];

export type ProjectPitchControllerFindAllV1Responses = {
    200: Array<ProjectPitchResponseDto>;
};

export type ProjectPitchControllerFindAllV1Response = ProjectPitchControllerFindAllV1Responses[keyof ProjectPitchControllerFindAllV1Responses];

export type ProjectPitchControllerCreateV1Data = {
    body: CreateProjectPitchDto;
    path?: never;
    query?: never;
    url: '/api/v1/project-pitch';
};

export type ProjectPitchControllerCreateV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type ProjectPitchControllerCreateV1Error = ProjectPitchControllerCreateV1Errors[keyof ProjectPitchControllerCreateV1Errors];

export type ProjectPitchControllerCreateV1Responses = {
    201: ProjectPitchResponseDto;
};

export type ProjectPitchControllerCreateV1Response = ProjectPitchControllerCreateV1Responses[keyof ProjectPitchControllerCreateV1Responses];

export type ProjectPitchControllerFindMyProjectPitchesV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project-pitch/me';
};

export type ProjectPitchControllerFindMyProjectPitchesV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type ProjectPitchControllerFindMyProjectPitchesV1Error = ProjectPitchControllerFindMyProjectPitchesV1Errors[keyof ProjectPitchControllerFindMyProjectPitchesV1Errors];

export type ProjectPitchControllerFindMyProjectPitchesV1Responses = {
    200: Array<ProjectPitchResponseDto>;
};

export type ProjectPitchControllerFindMyProjectPitchesV1Response = ProjectPitchControllerFindMyProjectPitchesV1Responses[keyof ProjectPitchControllerFindMyProjectPitchesV1Responses];

export type ProjectPitchControllerRemoveV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/project-pitch/{id}';
};

export type ProjectPitchControllerRemoveV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type ProjectPitchControllerRemoveV1Error = ProjectPitchControllerRemoveV1Errors[keyof ProjectPitchControllerRemoveV1Errors];

export type ProjectPitchControllerRemoveV1Responses = {
    200: GeneralOkResponseDto;
};

export type ProjectPitchControllerRemoveV1Response = ProjectPitchControllerRemoveV1Responses[keyof ProjectPitchControllerRemoveV1Responses];

export type ProjectPitchControllerFindOneV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/project-pitch/{id}';
};

export type ProjectPitchControllerFindOneV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type ProjectPitchControllerFindOneV1Error = ProjectPitchControllerFindOneV1Errors[keyof ProjectPitchControllerFindOneV1Errors];

export type ProjectPitchControllerFindOneV1Responses = {
    200: ProjectPitchResponseDto;
};

export type ProjectPitchControllerFindOneV1Response = ProjectPitchControllerFindOneV1Responses[keyof ProjectPitchControllerFindOneV1Responses];

export type ProjectPitchControllerUpdateV1Data = {
    body: UpdateProjectPitchDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/project-pitch/{id}';
};

export type ProjectPitchControllerUpdateV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type ProjectPitchControllerUpdateV1Error = ProjectPitchControllerUpdateV1Errors[keyof ProjectPitchControllerUpdateV1Errors];

export type ProjectPitchControllerUpdateV1Responses = {
    200: ProjectPitchResponseDto;
};

export type ProjectPitchControllerUpdateV1Response = ProjectPitchControllerUpdateV1Responses[keyof ProjectPitchControllerUpdateV1Responses];

export type SkillControllerFindAllV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/skill';
};

export type SkillControllerFindAllV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type SkillControllerFindAllV1Error = SkillControllerFindAllV1Errors[keyof SkillControllerFindAllV1Errors];

export type SkillControllerFindAllV1Responses = {
    200: Array<SkillResponseDto>;
};

export type SkillControllerFindAllV1Response = SkillControllerFindAllV1Responses[keyof SkillControllerFindAllV1Responses];

export type SkillControllerCreateV1Data = {
    body: CreateSkillDto;
    path?: never;
    query?: never;
    url: '/api/v1/skill';
};

export type SkillControllerCreateV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type SkillControllerCreateV1Error = SkillControllerCreateV1Errors[keyof SkillControllerCreateV1Errors];

export type SkillControllerCreateV1Responses = {
    200: SkillResponseDto;
};

export type SkillControllerCreateV1Response = SkillControllerCreateV1Responses[keyof SkillControllerCreateV1Responses];

export type SkillControllerSearchV1Data = {
    body?: never;
    path?: never;
    query: {
        q: string;
    };
    url: '/api/v1/skill/search';
};

export type SkillControllerSearchV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type SkillControllerSearchV1Error = SkillControllerSearchV1Errors[keyof SkillControllerSearchV1Errors];

export type SkillControllerSearchV1Responses = {
    200: Array<SkillResponseDto>;
};

export type SkillControllerSearchV1Response = SkillControllerSearchV1Responses[keyof SkillControllerSearchV1Responses];

export type YswsControllerFindAllV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ysws';
};

export type YswsControllerFindAllV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type YswsControllerFindAllV1Error = YswsControllerFindAllV1Errors[keyof YswsControllerFindAllV1Errors];

export type YswsControllerFindAllV1Responses = {
    200: Array<YsWsResponseDto>;
};

export type YswsControllerFindAllV1Response = YswsControllerFindAllV1Responses[keyof YswsControllerFindAllV1Responses];

export type YswsControllerFindActiveV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ysws/active';
};

export type YswsControllerFindActiveV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type YswsControllerFindActiveV1Error = YswsControllerFindActiveV1Errors[keyof YswsControllerFindActiveV1Errors];

export type YswsControllerFindActiveV1Responses = {
    200: Array<YsWsResponseDto>;
};

export type YswsControllerFindActiveV1Response = YswsControllerFindActiveV1Responses[keyof YswsControllerFindActiveV1Responses];

export type YswsControllerFindEndedV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ysws/ended';
};

export type YswsControllerFindEndedV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type YswsControllerFindEndedV1Error = YswsControllerFindEndedV1Errors[keyof YswsControllerFindEndedV1Errors];

export type YswsControllerFindEndedV1Responses = {
    200: Array<YsWsResponseDto>;
};

export type YswsControllerFindEndedV1Response = YswsControllerFindEndedV1Responses[keyof YswsControllerFindEndedV1Responses];

export type YswsControllerSearchV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query to search for
         */
        q: string;
    };
    url: '/api/v1/ysws/search';
};

export type YswsControllerSearchV1Errors = {
    /**
     * Client side error
     */
    '4XX': ErrorMessageDto;
    /**
     * Server side error
     */
    '5XX': ErrorMessageDto;
};

export type YswsControllerSearchV1Error = YswsControllerSearchV1Errors[keyof YswsControllerSearchV1Errors];

export type YswsControllerSearchV1Responses = {
    200: Array<YsWsResponseDto>;
};

export type YswsControllerSearchV1Response = YswsControllerSearchV1Responses[keyof YswsControllerSearchV1Responses];
